/* vbox mascot system: seeded colour, round bodies, and Motion-driven symbols. */
(function(global){
 'use strict';
 const COLORS=['#965FF0','#378EF5','#24C77A','#23C5BB','#FF8A38','#F5BC29','#F253B1','#F25564','#BE67E8','#60C989','#FF6F59','#1B2A41'];
 const MOODS=['idle','working','waiting','happy','laughing','angry','sleeping','waking'];
 const MACHINE={idle:{WORK:'working',SEND:'waiting',PRAISE:'happy',JOKE:'laughing',ERROR:'angry',SLEEP:'sleeping',WAKE:'waking'},working:{SEND:'waiting',DONE:'happy',ERROR:'angry',JOKE:'laughing',STOP:'idle',SLEEP:'sleeping'},waiting:{REPLY:'happy',TIMEOUT:'angry',WORK:'working',JOKE:'laughing',STOP:'idle',SLEEP:'sleeping'},happy:{JOKE:'laughing',WORK:'working',SEND:'waiting',ERROR:'angry',SETTLE:'idle',SLEEP:'sleeping'},laughing:{SETTLE:'happy',WORK:'working',ERROR:'angry',SLEEP:'sleeping'},angry:{CALM:'idle',PRAISE:'happy',WORK:'working',SLEEP:'sleeping'},sleeping:{WAKE:'waking',WORK:'waking'},waking:{READY:'idle',WORK:'working',SLEEP:'sleeping'}};
 const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
 const traits=seed=>{const h=hash(seed);return {shape:'circle',color:h%37===0?COLORS[11]:COLORS[Math.floor(h/8)%11],eyeSpread:((h>>>12)%7-3)*.35,eyeTilt:((h>>>17)%7-3)*.12,phase:(h%1000)/1000*6.283,blink:2.3+(h%190)/100,eyes:'A'}};
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const eyePath=p=>`M${p[0]} ${p[1]} C${p[2]} ${p[3]} ${p[4]} ${p[5]} ${p[6]} ${p[7]}`;
 const rawEyesFor=(mood,variant='A')=>{const spread=variant==='C'?1:0,L=39-spread,R=61+spread,lo=53;const line=(cx,side=1)=>[cx-2.5,lo-6*side,cx-1.2,lo-3*side,cx+1.2,lo+3*side,cx+2.5,lo+6*side];switch(mood){
  case 'curious':return [[L-.35,lo,L-.15,lo+.2,L+.15,lo+.2,L+.35,lo],[R-.35,lo,R-.15,lo+.2,R+.15,lo+.2,R+.35,lo]];
  case 'wink':return [line(L,1),[R-5,lo,R-2,lo,R+2,lo,R+5,lo]];
  case 'excited':return [[L-3.2,lo-9,L-2,lo-4,L+2,lo+4,L+3.2,lo+9],[R-3.2,lo-9,R-2,lo-4,R+2,lo+4,R+3.2,lo+9]];
  case 'working':return [[L-5,lo-1,L-2,lo-3,L+2,lo-2,L+5,lo],[R-5,lo,R-2,lo-2,R+2,lo-3,R+5,lo-1]];
  case 'waiting':return [line(L+2,1).map((v,i)=>i%2?v-8:v),line(R+2,-1).map((v,i)=>i%2?v-8:v)];
  case 'happy':return [[L-6,lo+3,L-3,lo-12,L+3,lo-12,L+6,lo+3],[R-6,lo+3,R-3,lo-12,R+3,lo-12,R+6,lo+3]];
  case 'laughing':return [[L-6,lo-7,L+3,lo-2,L+3,lo+1,L-6,lo+7],[R+6,lo-7,R-3,lo-2,R-3,lo+1,R+6,lo+7]];
  case 'angry':return [[L-6,lo-8,L-3,lo-5,L+3,lo+1,L+6,lo+4],[R-6,lo+4,R-3,lo+1,R+3,lo-5,R+6,lo-8]];
  case 'sleeping':return [[L-6,lo+1,L-2,lo+1,L+2,lo+1,L+6,lo+1],[R-6,lo+1,R-2,lo+1,R+2,lo+1,R+6,lo+1]];
  case 'waking':return [line(L,1),line(R,1)];
  default:return variant==='C'?[[L,49,L-1,53,L+1,61,L,65],[R,49,R-1,53,R+1,61,R,65]]:[line(L,1),line(R,1)];}};
 const eyesFor=(mood,variant='A',t=null)=>rawEyesFor(mood,variant).map((p,j)=>p.map((v,i)=>i%2===0?(j?61:39)+(v-(j?61:39))*.8+(j?1:-1)*(t?.eyeSpread||0)+2.5:52.5+(v-57)*(variant==='C'?.72:.64)+(j?1:-1)*(t?.eyeTilt||0)*(v-(j?61:39))));
 const MOOD_GLYPH={angry:'error'};
 const EXTRA_EVENT={DONE:['happy','happy'],PRAISE:['happy','happy'],THANKS:['happy','happy'],APPROVAL:['waiting',null],NEEDS_ATTENTION:['waiting',null],CRASH:['angry','error'],FAILED:['angry','error'],RETRY:['waiting',null],RESTART:['waking','surprised'],CLEAR_CONTEXT:['waking','surprised'],NEW_CHAT:['waking','surprised'],USAGE:['idle',null]};
 const glyphOne=kind=>{switch(kind){
  case 'happy':return '<path d="M-7 5 Q0 -7 7 5"/>';
  case 'surprised':return '<circle cx="0" cy="0" r="5.5"/>';
  case 'error':return '<path d="M-6 -6 L6 6 M6 -6 L-6 6"/>';
  case 'sleeping':return '<path d="M-6 -5 L6 -5 L-6 5 L6 5"/>';
  case 'focused':return '<circle cx="0" cy="0" r="2.3" fill="white" stroke="none"/>';
  default:return ''}};
 const glyphMarkup=kind=>kind?`<g class="vbox-mascot-glyphs" stroke="#fff" stroke-width="4.4" stroke-linecap="round" stroke-linejoin="round" fill="none"><g transform="translate(36 57)">${glyphOne(kind,0)}</g><g transform="translate(64 57)">${glyphOne(kind,1)}</g></g>`:'';
 const POINTS=64;
 const circlePoints=(radius=36,cx=50,cy=52)=>Array.from({length:POINTS},(_,i)=>{const a=-Math.PI/2+i*2*Math.PI/POINTS;return [cx+radius*Math.cos(a),cy+radius*Math.sin(a)]});
 const stemPath=t=>{const top=76-57*t,bottom=76-8*t,w=5*t,b=2.4*t,r=4*t;return `M${(50-w).toFixed(2)} ${(top+r).toFixed(2)} Q${(50-w).toFixed(2)} ${top.toFixed(2)} 50 ${top.toFixed(2)} Q${(50+w).toFixed(2)} ${top.toFixed(2)} ${(50+w).toFixed(2)} ${(top+r).toFixed(2)} L${(50+b).toFixed(2)} ${bottom.toFixed(2)} Q50 ${(bottom+3*t).toFixed(2)} ${(50-b).toFixed(2)} ${bottom.toFixed(2)} Z`};
 const pointsPath=pts=>{let d=`M${pts[0][0].toFixed(2)} ${pts[0][1].toFixed(2)}`;for(let i=0;i<pts.length;i++){const p0=pts[(i-1+pts.length)%pts.length],p1=pts[i],p2=pts[(i+1)%pts.length],p3=pts[(i+2)%pts.length];d+=` C${(p1[0]+(p2[0]-p0[0])/6).toFixed(2)} ${(p1[1]+(p2[1]-p0[1])/6).toFixed(2)} ${(p2[0]-(p3[0]-p1[0])/6).toFixed(2)} ${(p2[1]-(p3[1]-p1[1])/6).toFixed(2)} ${p2[0].toFixed(2)} ${p2[1].toFixed(2)}`}return d+' Z'};
 function svg(seed,mood='idle',mini=false,appearance={},expression=MOOD_GLYPH[mood]||null){const t=traits(seed),p=pointsPath(circlePoints(39)),variant=appearance.eyes||t.eyes,eyeMood={happy:'happy',surprised:'curious',sleeping:'sleeping',focused:'working'}[expression]||mood,eye=eyesFor(eyeMood,variant,t),gid='vb-mascot-hi-'+hash(seed);if(eyeMood!==mood)expression=null;return `<svg class="vbox-mascot vbox-mascot-eyes-${variant}${mini?' vbox-mascot-mini':''}" viewBox="-6 -6 112 112" width="100%" height="100%" preserveAspectRatio="xMidYMid meet" data-mood="${mood}" data-expression="${expression||''}" data-seed="${esc(seed)}" role="img" aria-label="${mood} mascot" ><defs><linearGradient id="${gid}" x1="0" y1="0" x2="0" y2="1" gradientUnits="objectBoundingBox"><stop stop-color="#fff" stop-opacity=".16"/><stop offset=".52" stop-color="#fff" stop-opacity=".03"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></linearGradient><linearGradient id="vb-comet"><stop stop-color="#FF6F59"/><stop offset=".35" stop-color="#F5BC29"/><stop offset=".7" stop-color="#24C77A"/><stop offset="1" stop-color="#378EF5"/></linearGradient></defs><g class="vbox-mascot-motion"><path class="vbox-mascot-comet" d="M8 65 Q30 61 48 53" fill="none" stroke="url(#vb-comet)" stroke-width="1" stroke-linecap="round" opacity="0"/><g class="vbox-mascot-body" ><path class="vbox-mascot-shape" d="${p}" fill="${mood==='angry'?'#FF6F59':mood==='sleeping'?'#a9a8bf':t.color}"/><path class="vbox-mascot-highlight" d="${p}" fill="url(#${gid})" pointer-events="none"/><g class="vbox-mascot-blush" opacity="0"><ellipse cx="27" cy="66" rx="7" ry="3.2"/><ellipse cx="73" cy="66" rx="7" ry="3.2"/></g><g class="vbox-mascot-eyes" opacity="${expression?0:1}"><path class="vbox-mascot-eye left" d="${eyePath(eye[0])}"/><path class="vbox-mascot-eye right" d="${eyePath(eye[1])}"/><circle class="vbox-mascot-glint" cx="34" cy="53" r="1.3"/><circle class="vbox-mascot-glint" cx="62" cy="53" r="1.3"/></g><g class="vbox-mascot-glyph-host">${glyphMarkup(expression)}</g></g><path class="vbox-mascot-bang-stem" d="${stemPath(0)}" fill="${t.color}"/><g class="vbox-mascot-dots" opacity="0"><circle class="vbox-mascot-dot-left" cx="50" cy="52" r="0" fill="${t.color}"/><circle class="vbox-mascot-dot-right" cx="50" cy="52" r="0" fill="${t.color}"/></g><circle class="vbox-mascot-notice" cx="79" cy="22" r="5" fill="#378EF5" stroke="#fff" stroke-width="2" opacity="0"/><g class="vbox-mascot-particles" opacity="0"><circle cx="24" cy="34" r="2" fill="#FF6F59"/><circle cx="77" cy="36" r="2" fill="#F5BC29"/><circle cx="25" cy="77" r="2" fill="#24C77A"/><circle cx="77" cy="74" r="2" fill="#378EF5"/></g></g></svg>`}
 const animate=global.Motion?.animate;
 if(!animate)throw Error('motion.js must load before mascot.js');
 const active=new Set();let forcedReduce=false;
 const reduce=matchMedia('(prefers-reduced-motion: reduce)');
 const observer=typeof IntersectionObserver==='undefined'?null:new IntersectionObserver(entries=>{for(const entry of entries){const mascot=entry.target.__vboxMascot;if(mascot){mascot.visible=entry.isIntersecting;mascot.updateVisibility()}}});
 // Chat re-renders temporary avatars. Release their timers and Motion controls
 // once a previously mounted SVG leaves the document.
 const detachedObserver=typeof MutationObserver==='undefined'?null:new MutationObserver(()=>{
  for(const mascot of active){
   if(mascot.svg.isConnected)mascot.wasMounted=true;
   else if(mascot.wasMounted)mascot.destroy();
  }
 });
 detachedObserver?.observe(document.documentElement,{childList:true,subtree:true});
 const quiet=()=>reduce.matches||forcedReduce||document.hidden;
 let morphClock=0;
 function morphFrame(now){if(!active.size){morphClock=0;return}morphClock=requestAnimationFrame(morphFrame);if(quiet())return;for(const mascot of active)mascot.frame(now)}
 document.addEventListener('visibilitychange',()=>{for(const mascot of active)mascot.updateVisibility()});
 reduce.addEventListener?.('change',()=>{for(const mascot of active)mascot.updateVisibility()});
 class Mascot{
  constructor(host,seed,{onMood,appearance={}}={}){
   this.host=host;this.seed=String(seed);this.traits=traits(seed);this.appearance=appearance;this.onMood=onMood||null;
   this.state='idle';this.expression=null;this.signal='idle';this.visible=true;this.dead=false;this.token=0;this.phase='settled';this.controls=new Set();this.timers=[];this.sleepScale=1;this.busyMode=hash(this.seed)%2?'ball':'dots';this.busyInterval=8000+hash(this.seed+'busy')%4001;this.busyRemaining=this.busyInterval;
   host.innerHTML=svg(seed,'idle',false,appearance);
   this.svg=host.querySelector('svg');if(host.classList.contains('avatar-mascot')||host.classList.contains('processing-mascot'))this.svg.classList.add('vbox-mascot-mini');this.svg.__vboxMascot=this;
   this.motion=this.svg.querySelector('.vbox-mascot-motion');this.body=this.svg.querySelector('.vbox-mascot-body');this.shapePath=this.svg.querySelector('.vbox-mascot-shape');this.highlight=this.svg.querySelector('.vbox-mascot-highlight');this.eyesGroup=this.svg.querySelector('.vbox-mascot-eyes');this.eyes=[...this.svg.querySelectorAll('.vbox-mascot-eye')];this.glyphHost=this.svg.querySelector('.vbox-mascot-glyph-host');this.blush=this.svg.querySelector('.vbox-mascot-blush');this.dots=this.svg.querySelector('.vbox-mascot-dots');this.dotLeft=this.svg.querySelector('.vbox-mascot-dot-left');this.dotRight=this.svg.querySelector('.vbox-mascot-dot-right');this.notice=this.svg.querySelector('.vbox-mascot-notice');this.bangStem=this.svg.querySelector('.vbox-mascot-bang-stem');this.particles=this.svg.querySelector('.vbox-mascot-particles');this.cometTrail=this.svg.querySelector('.vbox-mascot-comet');
   this.paths={home:pointsPath(circlePoints(39)),bangDot:pointsPath(circlePoints(4,50,82)),dot:pointsPath(circlePoints(5))};this.glanceCount=0;this.blinkedYet=false;this.expressionCount=0;
   this.breathPhase=this.traits.phase;this.breathSpeed=2*Math.PI/3.6;this.breathAccel=0;this.formAngle=0;this.bangAngle=0;this.stemProgress=0;this.faceScale=1;this.faceRadius=39;this.blinkScale=1;this.dotCenterRadius=5;this.lastFrame=0;
   this.currentPath=this.paths.home;this.setPath(this.paths.home);this.look=[0,0];this.wasMounted=false;
   this.pointerMove=e=>{if(quiet()||!this.visible||host.getBoundingClientRect().width<120||this.expression)return;const r=host.getBoundingClientRect();this.lookTo(((e.clientX-r.left)/r.width-.5)*5,((e.clientY-r.top)/r.height-.5)*3,.22)};
   this.pointerLeave=()=>this.lookTo(0,0,.3);
   host.addEventListener('pointermove',this.pointerMove);host.addEventListener('pointerleave',this.pointerLeave);observer?.observe(this.svg);active.add(this);if(!morphClock)morphClock=requestAnimationFrame(morphFrame);this.scheduleBlink();this.scheduleGlance();this.scheduleExpression();
  }
  track(control){this.controls.add(control);control.finished?.finally(()=>this.controls.delete(control)).catch(()=>{});return control}
  stopControls(){for(const control of this.controls)control.stop?.();this.controls.clear()}
  clearTimers(){for(const t of this.timers)clearTimeout(t);this.timers=[];clearTimeout(this.busyTimer);this.busyTimer=null;clearTimeout(this.expressionTimer);this.expressionTimer=null}
  timer(fn,ms){const t=setTimeout(fn,ms);this.timers.push(t);return t}
  setPath(d){this.currentPath=d;this.shapePath.setAttribute('d',d);this.highlight.setAttribute('d',d)}
  updateFaceTransform(radius=this.faceRadius){const scale=this.faceScale,maxShift=Math.max(0,radius*.82-19.5*scale),scan=this.signal==='busy'&&this.busyMode==='ball'?3.8*Math.sin(this.breathPhase*1.4):0,drift=this.signal==='idle'?.8*Math.sin(this.breathPhase*.8+this.traits.phase):0,driftY=this.signal==='idle'?.45*Math.sin(this.breathPhase*.62+this.traits.phase):0,x=Math.max(-maxShift,Math.min(maxShift,this.look[0]+scan+drift)),y=Math.max(-maxShift*.6,Math.min(maxShift*.6,this.look[1]+driftY));const pivot='translate(50 57) rotate('+(-this.formAngle).toFixed(2)+') scale('+scale.toFixed(3)+' '+(scale*this.blinkScale).toFixed(3)+') translate(-50 -57) translate('+x.toFixed(2)+' '+y.toFixed(2)+')';const glyph='translate(50 57) rotate('+(-this.formAngle).toFixed(2)+') scale('+scale.toFixed(3)+') translate(-50 -57) translate('+x.toFixed(2)+' '+y.toFixed(2)+')';this.eyesGroup.setAttribute('transform',pivot);this.glyphHost.setAttribute('transform',glyph)}
  frame(now){
   if(this.dead||!this.visible){this.lastFrame=now;return}
   const dt=this.lastFrame?Math.min(50,now-this.lastFrame)/1000:0;this.lastFrame=now;
   const sleep=this.signal==='sleeping',busy=this.signal==='busy',dots=busy&&this.busyMode==='dots';
   const target=2*Math.PI/(sleep?6.5:busy?2.5:3.6);
   this.breathAccel+=(18*(target-this.breathSpeed)-8*this.breathAccel)*dt;
   this.breathSpeed+=this.breathAccel*dt;this.breathPhase+=this.breathSpeed*dt;
   if(this.phase!=='settled'||dots||(this.signal==='asking'||this.signal==='failed')&&this.stemProgress>0)return;
   const base=sleep?.58:1,amplitude=sleep?.008:busy?.024:.02;
   const scale=base*(1+amplitude*(.5-.5*Math.cos(this.breathPhase)));
   this.motion.setAttribute('transform','translate(50 52) scale('+scale.toFixed(4)+') translate(-50 -52)');
   this.faceRadius=39;this.faceScale=1;this.formAngle=0;
   this.updateFaceTransform();if(this.signal==='idle')this.scheduleExpression();
  }
  setSleepScale(value){this.sleepScale=value;this.motion.setAttribute('transform','translate(50 52) scale('+value.toFixed(3)+') translate(-50 -52)')}
  morphPath(to,duration=.54){const from=this.currentPath;if(from===to)return Promise.resolve();const c=this.track(animate(from,to,{duration,ease:[.55,0,.2,1],onUpdate:v=>this.setPath(v)}));return c.finished.catch(()=>{})}
  morph(name,duration=.54){return this.morphPath(this.paths[name],duration)}
  fade(node,to,duration=.22){const from=Number(node.getAttribute('opacity')||0);const c=this.track(animate(from,to,{duration,ease:'easeInOut',onUpdate:v=>node.setAttribute('opacity',v.toFixed(3))}));return c.finished.catch(()=>{})}
  lookTo(x,y,duration){if(this.dead||quiet())return;const from=this.look.slice();this.track(animate(0,1,{duration,ease:'easeInOut',onUpdate:t=>{this.look=[from[0]+(x-from[0])*t,from[1]+(y-from[1])*t];this.updateFaceTransform()}}))}
  setEyes(mood,expression,instant=false){const eyeExpression={happy:'happy',surprised:'curious',sleeping:'sleeping',focused:'working'}[expression];if(eyeExpression){mood=eyeExpression;expression=null}this.expression=expression;this.svg.dataset.expression=expression||'';for(const control of this.eyeControls||[])control.stop?.();this.eyeControls=[];const target=eyesFor(mood,this.appearance.eyes||this.traits.eyes,this.traits);for(let i=0;i<2;i++){const eye=this.eyes[i],to=eyePath(target[i]);if(instant)eye.setAttribute('d',to);else this.eyeControls.push(this.track(animate(eye.getAttribute('d'),to,{duration:.3,ease:'easeInOut',onUpdate:v=>eye.setAttribute('d',v)})))}
   const newMarkup=glyphMarkup(expression);this.glyphHost.setAttribute('opacity','1');if(instant){this.glyphHost.innerHTML=newMarkup;this.eyesGroup.setAttribute('opacity',expression?'0':'1');return}
   const old=this.glyphHost.firstElementChild;if(newMarkup){const wrap=document.createElementNS('http://www.w3.org/2000/svg','g');wrap.innerHTML=newMarkup;wrap.setAttribute('opacity','0');this.glyphHost.append(wrap);this.fade(wrap,1,.22).then(()=>{if(!this.dead)old?.remove()})}else if(old)this.fade(old,0,.22).then(()=>old.remove());
   this.fade(this.eyesGroup,expression?0:1,.22);
  }
  tint(mood){return mood==='sleeping'?'#9EA7BB':mood==='angry'?'#FF6F59':this.traits.color}
  setColor(mood,instant=false){const to=this.tint(mood),from=this.shapePath.getAttribute('fill');if(instant)this.shapePath.setAttribute('fill',to);else this.track(animate(from,to,{duration:.3,onUpdate:v=>this.shapePath.setAttribute('fill',v)}));this.dotLeft.setAttribute('fill',to);this.dotRight.setAttribute('fill',to);this.bangStem.setAttribute('fill',to)}
  setStem(value){this.stemProgress=value;this.bangStem.setAttribute('d',stemPath(value))}
  animateStem(to,duration=.5){const from=this.stemProgress;const control=this.track(animate(from,to,{duration,ease:[.45,0,.2,1],onUpdate:v=>this.setStem(v)}));return control.finished.catch(()=>{})}
  resetDecor(){this.dots.setAttribute('opacity','0');this.dotLeft.setAttribute('cx','50');this.dotRight.setAttribute('cx','50');this.dotLeft.setAttribute('r','0');this.dotRight.setAttribute('r','0');this.setStem(0);this.particles.setAttribute('opacity','0');this.notice.setAttribute('opacity','0');this.sleepScale=1;this.formAngle=0;this.bangAngle=0;this.stemProgress=0;this.faceScale=1;this.motion.removeAttribute('transform')}
  async leaveDecor(token){const tasks=[];if(Number(this.dots.getAttribute('opacity'))>0){const centerFrom=this.dotCenterRadius;tasks.push(this.track(animate(1,0,{duration:.3,ease:'easeInOut',onUpdate:t=>{this.dotCenterRadius=centerFrom+(5-centerFrom)*t+.55*Math.sin(Math.PI*t);this.setPath(pointsPath(circlePoints(this.dotCenterRadius)));this.dotLeft.setAttribute('cx',(50-18*t).toFixed(2));this.dotRight.setAttribute('cx',(50+18*t).toFixed(2));this.dotLeft.setAttribute('r',(4*t).toFixed(2));this.dotRight.setAttribute('r',(4*t).toFixed(2))}})).finished.catch(()=>{}));tasks.push(this.fade(this.dots,0,.3))}if(Math.abs(this.bangAngle)>.01)tasks.push(this.track(animate(this.bangAngle,0,{duration:.38,ease:'easeInOut',onUpdate:v=>{this.bangAngle=v;this.motion.setAttribute('transform','rotate('+v.toFixed(2)+' 50 52)')}})).finished.catch(()=>{}));if(this.stemProgress>0)tasks.push(this.animateStem(0,.38));if(Number(this.notice.getAttribute('opacity'))>0)tasks.push(this.fade(this.notice,0,.2));if(Number(this.particles.getAttribute('opacity'))>0)tasks.push(this.fade(this.particles,0,.2));await Promise.all(tasks);if(this.dead||token!==this.token)return false;this.resetDecor();this.lookTo(0,0,.3);return true}
  async toHome(token){await this.morphPath(this.paths.home,.5);if(this.dead||token!==this.token)return false;return true}
  async dotsMode(token){this.fade(this.eyesGroup,0,.25);this.fade(this.glyphHost,0,.25);const straighten={finished:Promise.resolve()};this.dots.setAttribute('opacity','1');const split=this.track(animate(0,1,{duration:.6,ease:'easeInOut',onUpdate:t=>{const emerge=Math.max(0,(t-.35)/.65);this.dotLeft.setAttribute('cx',(50-18*emerge).toFixed(2));this.dotRight.setAttribute('cx',(50+18*emerge).toFixed(2));this.dotLeft.setAttribute('r',(4*emerge).toFixed(2));this.dotRight.setAttribute('r',(4*emerge).toFixed(2))}}));await Promise.all([this.morph('dot',.6),split.finished.catch(()=>{}),straighten.finished.catch(()=>{})]);if(this.dead||token!==this.token)return;this.formAngle=0;this.motion.removeAttribute('transform');this.dotCenterRadius=5;const pulseStart=performance.now();this.track(animate(0,1,{duration:.9,repeat:Infinity,ease:'linear',onUpdate:t=>{const elapsed=Math.min(1,(performance.now()-pulseStart)/300),ramp=elapsed*elapsed*(3-2*elapsed),wave=phase=>ramp*Math.max(0,Math.sin(2*Math.PI*(t-phase))),left=wave(0),middle=wave(1/3),right=wave(2/3);this.dotLeft.setAttribute('r',(4+1.4*left).toFixed(2));this.dotRight.setAttribute('r',(4+1.4*right).toFixed(2));this.dotLeft.setAttribute('opacity',(1-.38*ramp+.38*left).toFixed(2));this.dotRight.setAttribute('opacity',(1-.38*ramp+.38*right).toFixed(2));this.dotCenterRadius=5+1.75*middle;this.setPath(pointsPath(circlePoints(this.dotCenterRadius)))}}));this.phase='settled';this.scheduleBusy()}
  async ballMode(token){if(!await this.toHome(token))return;this.setEyes('idle',null);this.lastFrame=0;this.phase='settled';this.scheduleBusy()}
  scheduleBusy(){if(this.dead||quiet()||!this.visible||this.signal!=='busy'||this.busyTimer)return;this.busyStartedAt=Date.now();this.busyTimer=setTimeout(()=>{this.busyTimer=null;this.busyRemaining=this.busyInterval;this.busyMode=this.busyMode==='dots'?'ball':'dots';this.startSignal()},this.busyRemaining)}
  pauseBusy(){if(this.busyTimer){clearTimeout(this.busyTimer);this.busyTimer=null;this.busyRemaining=Math.max(100,this.busyRemaining-(Date.now()-this.busyStartedAt))}}
  async startSignal(){const token=++this.token;this.stopControls();this.blinkScale=1;this.clearTimers();this.phase='turning';const signal=this.signal;this.setColor(this.state,quiet());const wakingFromSleep=this.sleepScale<.9&&signal!=='sleeping';if(quiet()||!this.visible){this.needsResume=true;this.setPath(this.paths.home);this.resetDecor();this.setEyes(this.state,signal==='sleeping'?null:this.expression,true);if(quiet()&&signal==='sleeping')this.setSleepScale(.58);this.phase='settled';return}this.needsResume=false;if(wakingFromSleep){this.resetDecor();this.setSleepScale(.58);if(signal!=='starting'){const grow=this.track(animate(.58,1,{duration:.45,ease:'easeOut',onUpdate:v=>this.setSleepScale(v)}));await grow.finished.catch(()=>{});if(token!==this.token)return;this.sleepScale=1;this.motion.removeAttribute('transform')}}else if(this.stemProgress>0&&signal!=='asking'&&signal!=='failed'){const straight=this.track(animate(this.bangAngle,0,{duration:.65,ease:[.55,0,.2,1],onUpdate:v=>{this.bangAngle=v;this.motion.setAttribute('transform','rotate('+v.toFixed(2)+' 50 52)')}}));await Promise.all([this.animateStem(0,.45),straight.finished.catch(()=>{})]);if(token!==this.token)return;await this.morphPath(this.paths.home,.55);if(token!==this.token)return;this.resetDecor()}else if(signal==='busy'&&this.busyMode==='dots'&&Number(this.dots.getAttribute('opacity'))===0&&this.stemProgress===0){this.fade(this.notice,0,.25)}else if((signal==='asking'||signal==='failed')&&this.stemProgress===0&&Number(this.dots.getAttribute('opacity'))===0&&Number(this.notice.getAttribute('opacity'))===0&&Number(this.particles.getAttribute('opacity'))===0){this.lookTo(0,0,.3)}else if(!await this.leaveDecor(token))return;
   if(signal==='busy'){if(this.busyMode==='dots')await this.dotsMode(token);else await this.ballMode(token);return}
   if(signal==='sleeping'){this.fade(this.eyesGroup,0,.2);this.fade(this.glyphHost,0,.2);await this.morph('dot',.32);if(token!==this.token)return;const grow=this.track(animate(1,.58,{duration:.44,ease:'easeInOut',onUpdate:v=>this.setSleepScale(v)}));await Promise.all([this.morphPath(this.paths.home,.44),grow.finished.catch(()=>{})]);if(token!==this.token)return;this.setEyes('sleeping',null);this.lastFrame=0;this.phase='settled';return}
   if(signal==='asking'||signal==='failed'){
    this.fade(this.eyesGroup,0,.22);this.fade(this.glyphHost,0,.22);
    await this.morph('bangDot',.58);if(token!==this.token)return;
    await this.animateStem(1,.56);if(token!==this.token)return;
    const swayStart=performance.now();this.bangSway=this.track(animate(0,1,{duration:2.1,repeat:Infinity,ease:'linear',onUpdate:t=>{const amplitude=Math.min(1,(performance.now()-swayStart)/400);this.bangAngle=3*amplitude*Math.sin(2*Math.PI*t);this.motion.setAttribute('transform','rotate('+this.bangAngle.toFixed(2)+' 50 52)')}}));
    this.phase='settled';
    this.timer(async()=>{if(this.dead||this.signal!==signal)return;this.bangSway?.stop?.();this.phase='turning';const straighten=this.track(animate(this.bangAngle,0,{duration:.25,ease:'easeInOut',onUpdate:v=>{this.bangAngle=v;this.motion.setAttribute('transform','rotate('+v.toFixed(2)+' 50 52)')}}));await straighten.finished.catch(()=>{});if(this.dead||this.signal!==signal)return;this.motion.removeAttribute('transform');await this.animateStem(0,.45);if(this.dead||this.signal!==signal)return;await this.morphPath(this.paths.home,.56);if(this.dead||this.signal!==signal)return;this.setEyes(signal==='failed'?'angry':'curious',signal==='failed'?'error':null);this.lastFrame=0;this.phase='settled';this.timer(()=>{if(!this.dead&&this.signal===signal)void this.startSignal()},1900)},1400);return
   }
   if(signal==='starting'){this.fade(this.eyesGroup,0,.18);this.fade(this.glyphHost,0,.18);if(!wakingFromSleep){await this.morph('dot',.25);if(token!==this.token)return}this.particles.setAttribute('opacity','1');const grow=wakingFromSleep?this.track(animate(.58,1,{duration:.5,ease:'easeOut',onUpdate:v=>this.setSleepScale(v)})).finished.catch(()=>{}):Promise.resolve();await Promise.all([this.morphPath(this.paths.home,.5),grow]);if(token!==this.token)return;this.sleepScale=1;this.motion.removeAttribute('transform');this.setEyes('waking','surprised');this.fade(this.particles,0,.4);this.lastFrame=0;this.phase='settled';return}
   await this.morphPath(this.paths.home,.4);if(token!==this.token)return;this.setEyes(signal==='unread'?'waking':'idle',signal==='unread'?'surprised':null);if(signal==='unread'){this.notice.setAttribute('r','0');this.track(animate(0,5,{duration:.28,ease:'easeOut',onUpdate:v=>this.notice.setAttribute('r',v.toFixed(2))}))}this.fade(this.notice,signal==='unread'?1:0,.25);this.lastFrame=0;this.phase='settled';
  }
  async comet(){if(this.dead||quiet()||!this.visible||this.cometActive)return false;this.cometActive=true;const token=++this.token;this.stopControls();this.clearTimers();this.phase='turning';if(!await this.leaveDecor(token))return false;this.fade(this.eyesGroup,0,.18);this.fade(this.glyphHost,0,.18);await this.morph('dot',.25);if(this.dead||token!==this.token)return false;const travel=this.track(animate(0,1,{duration:.75,ease:'easeInOut',onUpdate:t=>{const arc=Math.sin(Math.PI*t),x=74*arc,y=-11*arc;this.motion.setAttribute('transform','translate('+x.toFixed(2)+' '+y.toFixed(2)+')');this.cometTrail.setAttribute('opacity',arc.toFixed(3));this.cometTrail.setAttribute('stroke-dashoffset',(-100*t).toFixed(2))}}));await travel.finished.catch(()=>{});if(this.dead||token!==this.token)return false;this.motion.removeAttribute('transform');this.cometTrail.setAttribute('opacity','0');await this.morphPath(this.paths.home,.36);if(this.dead||token!==this.token)return false;this.cometActive=false;const pending=this.pendingPose;this.pendingPose=null;if(pending)this.jump(...pending);else void this.startSignal();return true}
  send(evt){const next=MACHINE[this.state]?.[evt];return next?this.jump(next):false}
  showExpression(expression){return this.jump(this.state,expression,this.signal)}
  jump(mood,expression=MOOD_GLYPH[mood]||null,signal=null){if(this.dead||!MOODS.includes(mood))return false;const next=signal||({working:'busy',waiting:'asking',happy:'unread',angry:'failed',sleeping:'sleeping',waking:'starting'}[mood]||'idle');if(this.cometActive){this.pendingPose=[mood,expression,next];return true}if(this.state===mood&&this.signal===next&&this.phase==='settled')return false;const old=this.signal,flowing=this.phase==='settled'&&((old==='idle'&&next==='busy'&&this.busyMode==='ball')||(old==='busy'&&this.busyMode==='ball'&&next==='idle'));this.state=mood;this.expression=expression;this.signal=next;this.svg.dataset.mood=mood;this.svg.dataset.signal=next;this.svg.setAttribute('aria-label',mood+' mascot');this.busyRemaining=this.busyInterval;if(flowing){this.blinkScale=1;this.updateFaceTransform();clearTimeout(this.busyTimer);this.busyTimer=null;this.setColor(mood);this.setEyes('idle',null);if(next==='busy')this.scheduleBusy()}else void this.startSignal();this.onMood?.(mood,this);return true}
  updateVisibility(){if(this.dead)return;if(quiet()||!this.visible){this.pauseBusy();for(const c of this.controls)c.pause?.();if(quiet()){this.needsResume=true;this.stopControls();this.clearTimers();this.setPath(this.paths.home);this.resetDecor();this.setEyes(this.state,this.signal==='sleeping'?null:this.expression,true);if(this.signal==='sleeping')this.setSleepScale(.58);this.phase='settled'}}else{if(this.needsResume){void this.startSignal();return}for(const c of this.controls)c.play?.();if(this.signal==='busy'&&this.phase==='settled')this.scheduleBusy();this.scheduleBlink();this.scheduleGlance()}}
  blink(){if(this.dead||quiet()||!this.visible||this.signal!=='idle'||this.phase!=='settled')return;this.track(animate(this.blinkScale,.08,{duration:.19,ease:[.45,0,.2,1],onUpdate:v=>{if(this.signal!=='idle')return;this.blinkScale=v;this.updateFaceTransform()}})).finished?.then(()=>{if(!this.dead&&this.signal==='idle')this.track(animate(.08,1,{duration:.24,ease:[.45,0,.2,1],onUpdate:v=>{if(this.signal!=='idle')return;this.blinkScale=v;this.updateFaceTransform()}}))}).catch(()=>{})}
  scheduleBlink(){if(this.blinkTimer||this.dead)return;const delay=this.blinkedYet?2800+hash(this.seed+Date.now())%700:1400+hash(this.seed)%1300;this.blinkTimer=setTimeout(()=>{this.blinkTimer=null;if(!quiet()&&this.visible&&this.phase==='settled'&&this.signal==='idle'){this.blinkedYet=true;this.blink();if(hash(this.seed+Date.now())%5===0)this.timer(()=>this.blink(),470)}this.scheduleBlink()},delay)}
  scheduleGlance(){if(this.glanceTimer||this.dead)return;this.glanceTimer=setTimeout(()=>{this.glanceTimer=null;if(!quiet()&&this.visible&&this.phase==='settled'&&this.signal==='idle'){const n=hash(this.seed+Date.now());if(++this.glanceCount%3===0){this.lookTo(-7,-1,.42);this.timer(()=>this.lookTo(7,-1,.52),450);this.timer(()=>this.lookTo(0,0,.43),1100)}else{this.lookTo((n%5-2)*3.5,((n>>>4)%5-2)*1.15,.16);this.timer(()=>this.lookTo(0,0,.42),330)}}this.scheduleGlance()},800+hash(this.seed+Date.now())%1400)}
  scheduleExpression(){if(this.expressionTimer||this.dead||quiet()||!this.visible||this.signal!=='idle')return;const delay=6000+hash(this.seed+'expression'+this.expressionCount++)%6001;this.expressionTimer=setTimeout(()=>{this.expressionTimer=null;if(!this.dead&&!quiet()&&this.visible&&this.phase==='settled'&&this.signal==='idle'){const choices=['happy','wink','curious','excited'];const choice=choices[hash(this.seed+'moment'+this.expressionCount)%choices.length];this.setEyes(choice,null);this.timer(()=>{if(!this.dead&&this.signal==='idle'){this.setEyes('idle',null);this.scheduleExpression()}},850+hash(this.seed+'hold'+this.expressionCount)%450)}else this.scheduleExpression()},delay)}
  render(instant){if(instant){this.stopControls();this.setPath(this.paths.home);this.resetDecor();this.setEyes(this.state,this.signal==='sleeping'?null:this.expression,true);if(this.signal==='sleeping')this.setSleepScale(.58)}}
  destroy(){if(this.dead)return;this.dead=true;this.token++;this.stopControls();this.clearTimers();clearTimeout(this.blinkTimer);clearTimeout(this.glanceTimer);clearTimeout(this.expressionTimer);this.host.removeEventListener('pointermove',this.pointerMove);this.host.removeEventListener('pointerleave',this.pointerLeave);observer?.unobserve(this.svg);active.delete(this);this.svg.remove()}
 }
 global.VBoxMascot={Mascot,svg,miniSVG:(seed,mood='idle',expression=MOOD_GLYPH[mood]||null)=>svg(seed,mood,true,{},expression),setReducedMotion:value=>{forcedReduce=!!value;for(const mascot of active)mascot.updateVisibility()},traits,MACHINE,shapes:['circle'],colors:COLORS,moods:MOODS};
})(window);
