const api=window.VBoxMascot,all=[];
function add(host,seed,mood,expression,signal){const m=new api.Mascot(host,seed);all.push(m);if(mood!=='idle')m.jump(mood,expression,signal);return m}
const hero=add(document.querySelector('#hero'),'vbox-hero','idle');
const states=[['idle','idle',null,'idle'],['busy dots','working','focused','busy'],['asking','waiting','surprised','asking'],['unread','happy','surprised','unread'],['failed','angry','error','failed'],['hibernated','sleeping','sleeping','sleeping'],['starting','waking','surprised','starting']];
for(const [label,mood,expression,signal] of states){const button=document.createElement('button');button.textContent=label;button.onclick=()=>{hero.busyMode='dots';hero.jump(mood,expression,signal)};document.querySelector('#controls').append(button)}
const polygonButton=document.createElement('button');polygonButton.textContent='busy polygons';polygonButton.onclick=()=>{hero.busyMode='polygon';if(hero.signal==='busy')void hero.startSignal();else hero.jump('working','focused','busy')};document.querySelector('#controls').append(polygonButton);
for(const glyph of ['happy','surprised','error','sleeping','focused']){const card=document.createElement('article'),pair=document.createElement('div'),large=document.createElement('div'),small=document.createElement('div'),label=document.createElement('small');pair.className='glyph-pair';large.className='glyph-large';small.className='glyph-small';large.innerHTML=api.svg('glyph-demo','idle',false,{},glyph);small.innerHTML=api.svg('glyph-demo','idle',true,{},glyph);label.textContent=glyph;pair.append(large,small);card.append(pair,label);document.querySelector('#glyphs').append(card)}
for(const [label,mood,expression,signal] of states){const card=document.createElement('article'),pair=document.createElement('div'),large=document.createElement('div'),small=document.createElement('div'),caption=document.createElement('small');pair.className='glyph-pair';large.className='glyph-large';small.className='glyph-small';pair.append(large,small);card.append(pair);caption.textContent=label;card.append(caption);document.querySelector('#props').append(card);add(large,'state-'+label,mood,expression,signal);add(small,'state-'+label,mood,expression,signal);small.querySelector('svg')?.classList.add('vbox-mascot-mini')}
for(let i=0;i<24;i++){const card=document.createElement('article');card.className='card';const host=document.createElement('div');host.className='host';card.append(host);const name=document.createElement('small');name.textContent='box '+String(i+1).padStart(2,'0');card.append(name);document.querySelector('#grid').append(card);add(host,'box-'+i,'idle')}
for(let i=0;i<12;i++){const host=document.createElement('div');host.className='host';document.querySelector('#small').append(host);add(host,'box-'+i,'idle')}
for(const [label,mood,expression,signal] of states){const card=document.createElement('article'),host=document.createElement('div');host.className='host';card.append(host,label);document.querySelector('#moods').append(card);add(host,'mood-'+label,mood,expression,signal)}
document.querySelector('#reduce').onchange=e=>{api.setReducedMotion(e.target.checked);for(const m of all)m.render(true)};
